Q 1.Write a Python Program to Add Two Matrices?

In [2]:
import numpy as np
matrix1 = np.array([[4,5,6],[3,8,0],[2,6,3]])
matrix2 = np.array([[7,8,9],[6,5,9],[5,7,9]])
matrix_sum = np.add(matrix1,matrix2)
print("The Sum of the matrices \n\n{} and \n\n{} is \n\n{}".format(matrix1,matrix2,matrix_sum))

The Sum of the matrices 

[[4 5 6]
 [3 8 0]
 [2 6 3]] and 

[[7 8 9]
 [6 5 9]
 [5 7 9]] is 

[[11 13 15]
 [ 9 13  9]
 [ 7 13 12]]


Q2.Write a Python Program to Multiply Two Matrices?

In [3]:
import numpy as np
matrix1 = np.array([[4,5,6],[7,8,9],[6,5,9]])
matrix2 = np.array([[1,2,3],[6,5,4],[9,8,7]])
matrix_product = np.dot(matrix1,matrix2)
print("The Product of the matrices \n\n{} and \n\n{} is \n\n{}".format(matrix1,matrix2,matrix_product))

The Product of the matrices 

[[4 5 6]
 [7 8 9]
 [6 5 9]] and 

[[1 2 3]
 [6 5 4]
 [9 8 7]] is 

[[ 88  81  74]
 [136 126 116]
 [117 109 101]]


Q3.Write a Python Program to Transpose a Matrix?

In [4]:
import numpy as np
matrix1 = np.array([[11,12,13],[14,15,16],[17,18,19]])
matrix_transpose = np.transpose(matrix1)
print("The Transpose of the matrix \n\n{} is \n\n{} ".format(matrix1,matrix_transpose))

The Transpose of the matrix 

[[11 12 13]
 [14 15 16]
 [17 18 19]] is 

[[11 14 17]
 [12 15 18]
 [13 16 19]] 


Q4.Write a Python Program to Sort Words in Alphabetic Order?

In [5]:
def words_sorter():
    user_input = input("Enter a string of words to sort them in alphabetical order: ")
    print()
    sorted_list = sorted(user_input.lower().split())
    print(' '.join(sorted_list))
words_sorter()

Enter a string of words to sort them in alphabetical order: sare jaha se accha hindustan hamara 

accha hamara hindustan jaha sare se


Q5.Write a Python Program to Remove Punctuation From a String?

In [6]:
def punctuation_remover():
    import string
    user_input = input("Enter the string from which you want to remove the punctuation: ")
    output = ''.join([i for i in user_input if i not in string.punctuation])
    return output
punctuation_remover()

Enter the string from which you want to remove the punctuation: fsds course is very good for future !@#$%^&*


'fsds course is very good for future '